syntax on
set nohlsearch
set cursorline
set number
set title
set tabstop=4
set expandtab
set shiftwidth=4
set smartindent
set list
set listchars=tab:»-,trail:-,eol:↲,extends:»,precedes:«,nbsp:%
set nrformats-=octal
set hidden
set whichwrap=b,s,[,],<,>
set backspace=indent,eol,start
set laststatus=2
set statusline=%F/%l/%c%=
